name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

concurrency:
  group: gh-pages-workflow
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          #node-version-file: .nvmrc
          node-version: 20.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Copy files
        run: |
          cp CNAME build/CNAME
          cp robots.txt build/robots.txt
          
      - name: Build Nginx Config
        run: |
          cd nginxconfig
          npm ci
          npm test
          npm run build
          cd ../
          mkdir build/nginx
          cp -r /nginxconfig/dist/* build/nginx

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Deploy master to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages
          clean: true
          single-commit: true

#      - name: Deploy
#        uses: s0/git-publish-subdir-action@master
#        env:
#          REPO: self
#          BRANCH: gh-pages
#          FOLDER: build
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
