name: Build

'on':
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Create node environment
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Install packages and build application
        run: |
          npm i
          npm run build
          cp CNAME build/CNAME
          cp robots.txt build/robots.txt
      - name: Deploy
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: build
          SSH_PRIVATE_KEY: '${{ secrets.DEPLOY_PRIVATE_KEY }}'